FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application files
COPY . .

# Copy environment variables file
COPY .env ./

# Copy keys directory
COPY keys/ ./keys/

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["node", "src/app.js"]
