FROM node:23

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the application files
COPY . .


# Start the application
CMD ["node", "src/app.js"]
