services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/config/server.properties:/etc/kafka/server.properties
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:${KAFKA_PORT},EXTERNAL://${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:9093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:${KAFKA_PORT},EXTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
      - "9093:9093" #External port
    
  donor-service:
    build:
      context: ./services/donor-service
      dockerfile: Dockerfile
    container_name: donor-service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:${KAFKA_PORT}
      MONGO_URI: ${MONGO_URI} 
    volumes:
      - ./services/donor-service:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
  
  charity-service:
    build:
      context: ./services/charity-service
      dockerfile: Dockerfile
    container_name: charity-service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:${KAFKA_PORT}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./services/charity-service:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
    
  authentication-service:
    build:
      context: ./services/authentication-service
      dockerfile: Dockerfile
    container_name: authentication-service
    depends_on:
      - kafka
      - charity-service
      - donor-service
    environment:
      KAFKA_BROKER: ${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_EXTERNAL_PORT}
      MONGO_URI: ${MONGO_URI}
      RSA_PRIVATE_KEY_PATH: ${RSA_PRIVATE_KEY_PATH}
      JWE_PUBLIC_KEY_PATH: ${JWE_PUBLIC_KEY_PATH}
      JWS_PRIVATE_KEY_PATH: ${JWS_PRIVATE_KEY_PATH}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./services/authentication-service:/usr/src/app
      - /usr/src/app/node_modules
      - ./keys:/usr/src/app/keys
    command: ["npm", "start"]

