services:
  donor-service:
    build:
      context: ./services/donor-service
      dockerfile: Dockerfile
    container_name: donor-service
    environment:
      KAFKA_BROKER: ${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_EXTERNAL_PORT}
      MONGO_URI: ${MONGO_URI} 
    volumes:
      - ./services/donor-service:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
  
  charity-service:
    build:
      context: ./services/charity-service
      dockerfile: Dockerfile
    container_name: charity-service
    environment:
      KAFKA_BROKER: ${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_EXTERNAL_PORT}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./services/charity-service:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
    
  authentication-service:
    build:
      context: ./services/authentication-service
      dockerfile: Dockerfile
    container_name: authentication-service
    depends_on:
      - charity-service
      - donor-service
    environment:
      KAFKA_BROKER: ${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_EXTERNAL_PORT}
      MONGO_URI: ${MONGO_URI}
      RSA_PRIVATE_KEY_PATH: ${RSA_PRIVATE_KEY_PATH}
      JWE_PUBLIC_KEY_PATH: ${JWE_PUBLIC_KEY_PATH}
      JWS_PRIVATE_KEY_PATH: ${JWS_PRIVATE_KEY_PATH}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./services/authentication-service:/usr/src/app
      - /usr/src/app/node_modules
      - ./keys:/usr/src/app/keys
    command: ["npm", "start"]

  statistics-service:
    build:
      context: ./services/statistic-service
      dockerfile: Dockerfile
    container_name: statistic-service
    depends_on:
      - charity-service
      - donor-service
    environment:
      KAFKA_BROKER: ${KAFKA_EXTERNAL_ADVERTISED_HOSTNAME}:${KAFKA_EXTERNAL_PORT}
      MONGO_URI: ${MONGO_URI}
      TEAM_A_API_GATEWAY: ${TEAM_A_API_GATEWAY}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    volumes:
      - ./services/statistic-service:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]
