# Use the official Node.js image as the base image
FROM node:23

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package files to the container
COPY package.json /usr/src/app/

# Install dependencies 
RUN npm install 

# Copy the entire application code into the container
COPY . .

# Start the application
CMD ["node", "src/server.js"]